#!/bin/bash
#script created by wildyvpn
clear
clear
clear
clear
sleep 0,1
clear && neofetch
echo -e "Script By WildySheverando / WildyVPN
echo -e ""
echo -e "============================ SSH / OVPN =================================="
echo -e "* menu                     : Menampilkan Daftar Semua Menu               *"
echo -e "* utama                    : Menampilkan Menu Menu yang ada              *"
echo -e "* tambah                   : Membuat akun SSH & OVPN Baru                *"
echo -e "* percobaan                : Membuat akun SSH & OVPN Percobaan           *"
echo -e "* hapus                    : Menghapus akun Yang Bandel                  *"
echo -e "* cek                      : Cek Siapa Saja Yang Login                   *"
echo -e "* anggota                  : Cek Semua Anggota Di SSH / OVPN             *"
echo -e "============================== SPECIAL ===============!==================="
echo -e "* addv2ray                 : Menambah Akun V2ray (Wajib Ada Domain)      *"
echo -e "* delv2ray                 : Menghapus Akun V2ray                        *"
echo -e "* tambahwg                 : Menambah Akun Wireguard                     *"
echo -e "* hapuswg                  : Menghapus Akun Wireguard                    *"
echo -e "* tambahssr                : Menambah Akun Sodosok SSR                   *"
echo -e "* hapusssr                 : Menghapus Akun Sodosok SSR                  *"
echo -e "============================== SPECIAL ==================================="
echo -e "*               WILDY VPN AUTO INSTALL SSH / OVPN SCRIPT                 *"
echo -e "============================ Menu System ================================="
echo -e "* vnstat                   : Melihat Pemakian Bandwidth Pada Pipies      *"
echo -e "* restart                  : Merestart Semua Menu VPN                    *"
echo -e "* ressh                    : Merestart SSH                               *"
echo -e "* redrop                   : Merestart Dropbear                          *"
echo -e "* resquid                  : Merestart Squid Proxy                       *"
echo -e "* reovpn                   : Merestart OVPN Service                      *"
echo -e "* restun                   : Merestart Stunnel                           *"
echo -e "* remin                    : Merestart Webmin                            *"
echo -e "* reboot                   : Merestart Server VPS                        *" 
echo -e "* ujicoba                  : Mencoba Kecepatan Jaringan                  *"
echo -e "* info                     : Menampilkan Informasi System                *"
echo -e "* about                    : Menampilkan Informasi Script                *"
echo -e "* update                   : Mengupdate Semua Package                    *"
echo -e "* exit                     : Logout Dari Server                          *"
echo -e "============================= Tambahan ==================================="
echo -e "* installvpn               : Meningstall Package L2TP / PPTP By Horass   *"
echo -e "* addpptp                  : Menambah Akun PPTP                          *"
echo -e "* delpptp                  : Menghapus Akun PPTP                         *"
echo -e "* addvpn                   : Menambah / Membuat Akun L2TP                *"
echo -e "* delvpn                   : Menghapus AKun L2TP                         *"
echo -e "============================= Tambahan ==================================="
echo -e "*                                                                        *"
echo -e "*             Script Created By WILDY SHEVERANDO / Wildy VPN             *"
echo -e "*                         WA = 0896-3528-4000                            *"
echo -e "*                                                                        *"
echo -e "============================= Thanks You ================================="
